name: barikoi_api
version: 0.0.2
description: Barikoi API Client
environment:
    sdk: '>=2.12.0 <3.0.0'
dependencies:
    dio: ^4.0.4
    built_value: ^8.1.4
    built_collection: ^5.1.1
dev_dependencies:
    built_value_generator: ^8.1.4
    build_runner: ^2.1.7

